### ISSUE TITLE
程序有很大的问题

### ISSUE THREAD

**Issue by SeqCrafter** [zhangtaolab/CRISPRMatch#1]
作者您好：
        该程序使用conda安装bwa等程序，但是运行在集群等封闭式环境的状态下，很难使用，而且conda也无法简单安装bwa，picard等。另外，picard程序运行应该使用类似java -jar  $picard 这种形式，怎么可以直接运行呢？可代码中却直接调用程序路径执行的方式，这种方式怎么可能成功运行？

**Comment by wushufly** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: Cannot add sequence that already exists in SAMSequenceDictionary

**Comment by wushufly** [comment]
Traceback (most recent call last):
 File "/Bigdata/cuizf/bin/CRISPRMatch/CRISPRMatch_paired.py", line 513, in <module>
main()
File "/Bigdata/cuizf/bin/CRISPRMatch/CRISPRMatch_paired.py", line 95, in main
mut_rate.rate_cal(args.input, args.groupinfo, args.genome, args.result, args.saved)
File "/Bigdata/cuizf/bin/CRISPRMatch/CMlib/mut_rate.py", line 32, in rate_cal
 stranddict[groupinfor.loc[idy].rep1] = groupinfor.loc[idy].strand
File "/Database/Software/Anaconda/envs/crispr/lib/python3.6/site-packages/pandas/core/generic.py", line 5057, in __
return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'strand'

**Comment by panxiaoguang** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: Cannot add sequence that already exists in SAMSequenceDictionary

你这程序报错应该是输入文件有问题吧，它测试文件你试过吗
