### ISSUE TITLE
UnboundLocalError: local variable 'flashversion' referenced before assignment

### ISSUE THREAD

**Issue by N-yating** [zhangtaolab/CRISPRMatch#4]
你好，按照原先的按照教程，已经成功地安装上了所示包，但是例子运行依旧报错，请问您能帮忙解决吗？

**Comment by N-yating** [comment]
Traceback (most recent call last):
  File "CRISPRMatch.py", line 507, in <module>
    main()
  File "CRISPRMatch.py", line 18, in main
    args = check_options(get_options())
  File "CRISPRMatch.py", line 355, in check_options
    print("flash version:", args.flash, flashversion)
UnboundLocalError: local variable 'flashversion' referenced before assignment
(crmatch) [bgi_nieyt@mgt13 CRISPRMatch-master]$ vim test_single_long.sh 
(crmatch) [bgi_nieyt@mgt13 CRISPRMatch-master]$ sh test_single_long.sh 
########################################
Traceback (most recent call last):
  File "CRISPRMatch.py", line 507, in <module>
    main()
  File "CRISPRMatch.py", line 18, in main
    args = check_options(get_options())
  File "CRISPRMatch.py", line 355, in check_options
    print("flash version:", args.flash, flashversion)
UnboundLocalError: local variable 'flashversion' referenced before assignment

**Comment by forrestzhang** [comment]
我们有新工具，你可以试试https://bioinfor.yzu.edu.cn/software/crisprstitch
